# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-12 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panorama', '0004_auto_20150310_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panorama',
            options={'verbose_name': 'panorama', 'verbose_name_plural': 'panoramas'},
        ),
        migrations.AlterModelOptions(
            name='reference',
            options={'verbose_name': 'reference', 'verbose_name_plural': 'references'},
        ),
        migrations.AlterModelOptions(
            name='referencepoint',
            options={'verbose_name': 'reference point', 'verbose_name_plural': 'reference points'},
        ),
        migrations.AddField(
            model_name='referencepoint',
            name='kind',
            field=models.CharField(choices=[('waiting', 'waiting'), ('subscriber', 'subscriber'), ('other', 'other')], default='waiting', max_length=255, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='panorama',
            name='image_height',
            field=models.PositiveIntegerField(default=0, verbose_name='image height'),
        ),
        migrations.AlterField(
            model_name='panorama',
            name='image_width',
            field=models.PositiveIntegerField(default=0, verbose_name='image width'),
        ),
        migrations.AlterField(
            model_name='panorama',
            name='references',
            field=models.ManyToManyField(related_name='referenced_panorama', through='panorama.Reference', to='panorama.ReferencePoint', verbose_name='references'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='panorama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panorama_references', to='panorama.Panorama', verbose_name='panorama'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='reference_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refpoint_references', to='panorama.ReferencePoint', verbose_name='reference point'),
        ),
        migrations.AlterUniqueTogether(
            name='reference',
            unique_together=set([]),
        ),
    ]
